# Playbook with multiple tasks
# Lab: modify playbook to open http in firewall on rhs2.contoso.com
---
- name: Install and start Apache webserver
  hosts: rhs2.contoso.com
  tasks:
    - name: httpd package is present
      yum:
        name: httpd
        state: present
    - name: Create some web content and add to index.html
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
    - name: httpd is started and enabled
      service:
        name: httpd
        state: started
        enabled: true
...