---
- name: Loops With Variable Example
  hosts: rhs2.contoso.com
  vars:
    mail_services:
      - postfix
      - dovecot
  tasks:
    - name: Postfix and Dovecot are running
      service:
        name: "{{ item }}"
        state: started
      loop: "{{ mail_services }}"
...