---
- name: Simple Loop Example
  hosts: rhs2.contoso.com

  tasks:
    - name: Install Mail Packages
      yum:
        name: "{{ item }}"
        state: latest

      loop:
        - postfix
        - dovecot
...