# Module: file
# set selinux permissions
---
- name: First Play
  hosts: rhs2.contoso.com

  tasks:
    - name: First Task
      file:
        path: /tmp/testfile
        setype: samba_share_t
        state: touch

    - name: Second Task
      command: ls -Z /tmp/testfile
      register: ls

    - name: Third Task
      debug: var=ls.stdout_lines
...